services:
  frontend:
    build:
      context: ./nginstaclone  
      dockerfile: Dockerfile
    ports:
      - "4200:4200"        
    volumes:
      - ./nginstaclone:/app   
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./instclonebackend  
      dockerfile: Dockerfile
    ports:
      - "4000:4000"       
    volumes:
      - ./instclonebackend:/app    
    environment:
      - NODE_ENV=development 
      - MONGO_URI=mongodb://mongo:27017/instclone  
    depends_on:
      - mongo              
  # MongoDB service
  mongo:
    image: mongo:latest         
    ports:
      - "27017:27017"           
    volumes:
      - mongo-data:/data/db     

volumes:
  mongo-data:                    
